#!/usr/bin/env bash
# Regression test for vstack#586: installed/refreshed orch start workflow must
# remain byte-identical to canonical source and clean under downstream-relevant
# markdownlint rules.
set -euo pipefail

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$TEST_DIR/../../.." && pwd)"
CLI_DIR="$REPO_ROOT/cli"
CANONICAL="$REPO_ROOT/skills/orch/workflows/start.md"
MARKDOWNLINT_CLI_VERSION="0.49.1"

TMP_ROOT="$(cd "$(mktemp -d)" && pwd -P)"
trap 'rm -rf "$TMP_ROOT"' EXIT
PROJECT="$TMP_ROOT/project"
GENERATED="$PROJECT/.agents/skills/orch/workflows/start.md"
GENERATED_RELATIVE=".agents/skills/orch/workflows/start.md"
SNAPSHOT="$TMP_ROOT/start-after-add.md"

PASS=0
FAIL=0

pass() {
  PASS=$((PASS + 1))
  printf '  ok    %s\n' "$1"
}

fail() {
  FAIL=$((FAIL + 1))
  printf '  FAIL  %s\n' "$1"
}

assert_generated_matches() {
  local phase="$1"
  if cmp -s "$CANONICAL" "$GENERATED"; then
    pass "$phase output matches canonical start workflow"
  else
    fail "$phase output differs from canonical start workflow"
    diff -u "$CANONICAL" "$GENERATED" || true
  fi
}

lint_generated() {
  local phase="$1"
  local -a runner

  if command -v markdownlint >/dev/null 2>&1; then
    runner=(markdownlint)
  elif command -v npx >/dev/null 2>&1; then
    runner=(
      npx
      --yes
      "--package=markdownlint-cli@$MARKDOWNLINT_CLI_VERSION"
      --
      markdownlint
    )
  else
    fail "$phase output could not be linted: markdownlint and npx are unavailable"
    return
  fi

  # These three style rules are intentionally disabled by the downstream
  # repository from #586. All other default rules, including MD022/55/56, run.
  if (cd "$PROJECT" && "${runner[@]}" --disable MD013 MD031 MD060 -- \
    "$GENERATED_RELATIVE"); then
    pass "$phase output passes markdownlint"
  else
    fail "$phase output fails markdownlint"
  fi
}

echo "=== generated orch start markdownlint ==="

cargo build --quiet --manifest-path "$CLI_DIR/Cargo.toml"
mkdir -p "$PROJECT/.agents"

if (cd "$PROJECT" && "$CLI_DIR/target/debug/vstack" add "$REPO_ROOT" \
  --skill orch --copy -y) >"$TMP_ROOT/add.log" 2>&1; then
  pass "orch skill installs into the fixture project"
else
  fail "orch skill installation succeeds"
  sed 's/^/        /' "$TMP_ROOT/add.log"
fi

if [[ -f "$GENERATED" ]]; then
  pass "install generates the orch start workflow"
  assert_generated_matches "install"
  lint_generated "install"
  cp "$GENERATED" "$SNAPSHOT"
else
  fail "install generates the orch start workflow"
fi

if (cd "$PROJECT" && "$CLI_DIR/target/debug/vstack" refresh \
  --scope project -v) >"$TMP_ROOT/refresh-one.log" 2>&1; then
  pass "first project refresh succeeds"
else
  fail "first project refresh succeeds"
  sed 's/^/        /' "$TMP_ROOT/refresh-one.log"
fi

if [[ -f "$GENERATED" ]]; then
  assert_generated_matches "first refresh"
  if cmp -s "$SNAPSHOT" "$GENERATED"; then
    pass "first refresh preserves generated bytes"
  else
    fail "first refresh changes generated bytes"
  fi
  lint_generated "first refresh"
fi

if (cd "$PROJECT" && "$CLI_DIR/target/debug/vstack" refresh \
  --scope project -v) >"$TMP_ROOT/refresh-two.log" 2>&1; then
  pass "second project refresh succeeds"
else
  fail "second project refresh succeeds"
  sed 's/^/        /' "$TMP_ROOT/refresh-two.log"
fi

if [[ -f "$GENERATED" ]]; then
  assert_generated_matches "second refresh"
  if cmp -s "$SNAPSHOT" "$GENERATED"; then
    pass "second refresh is byte-idempotent"
  else
    fail "second refresh changes generated bytes"
  fi
  lint_generated "second refresh"
fi

if grep -Eq 'skill[[:space:]]+orch.*\(unchanged\)' \
  "$TMP_ROOT/refresh-two.log"; then
  pass "second refresh reports orch unchanged"
else
  fail "second refresh reports orch unchanged"
fi

if (cd "$PROJECT" && "$CLI_DIR/target/debug/vstack" verify \
  --scope project orch) >"$TMP_ROOT/verify.log" 2>&1; then
  pass "verify confirms the refreshed orch install"
else
  fail "verify confirms the refreshed orch install"
  sed 's/^/        /' "$TMP_ROOT/verify.log"
fi

printf 'pass: %d   fail: %d\n' "$PASS" "$FAIL"
[[ "$FAIL" -eq 0 ]]
